model:
    name: 'MLPRULPredictor'
    in_channels: 1
    channels: 32
    input_height: 1
    input_width: 1000
    epochs: 5000
    batch_size: 128
    evaluate_freq: 100
train_test_split:
    name: 'RandomTrainTestSplitter'
    cell_data_path:
        - 'data/processed/CALCE'
        - 'data/processed/RWTH'
        - 'data/processed/UL_PUR'
        - 'data/processed/HNEI'
        - 'data/processed/MATR'
        - 'data/processed/HUST'
feature:
    name: 'FullModelFeatureExtractor'
    interp_dims: 1000
    critical_cycles:
        - 2
        - 9
        - 99
    use_precalculated_qdlin: True
label:
    name: 'RULLabelAnnotator'
feature_transformation:
    name: 'ZScoreDataTransformation'
label_transformation:
    name: 'SequentialDataTransformation'
    transformations:
        - name: 'LogScaleDataTransformation'
        - name: 'ZScoreDataTransformation'
